services:
    pdo.database_connection:
      class: PDO
      arguments: [ 'mysql:dbname=%starter.dbname%;host=%starter.dbhost%;port=%starter.dbport%', '%starter.dbusername%', '%starter.dbpassword%', {3: 2} ]
      # 3:2 will make PDO throw exceptions

    starter.controller.product:
      class: Application\Http\Controller\Product