services:
    pdo.database_connection:
      class: PDO
      arguments: [ 'mysql:dbname=%starter.dbname%;host=%starter.dbhost%;port=%starter.dbport%', '%starter.dbusername%', '%starter.dbpassword%' ]